sudo: required
services:
  - docker

before_install:
  - docker build -t vijayanands/docker-react -f Dockerfile.dev .

 
script:
  - docker run -e CI=true vijayanands/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-854198326494"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
